### PR TITLE
feat(button): Add button component

### PR DESCRIPTION
**Pull request by vogelino**
It was a pain to work with liquid but I finally did it. This new button component accepts the following props:
- tag (Html tag to use, defaults to anchor)
- text: The button text content
- variant: One of 'primary' or 'secondary'
- inverted: Whether the button is on an inverted background
- And those typical html props:
  - href
  - rel
  - download
  - title
  - aria-label
  - target
  - id

### CODE REVIEW

**Review by raphael-arce — COMMENTED** [review]
@vogelino  @dnsos opinionated question: How would you guys feel about having multiple buttons that have one design (e.g. `button-primary`, `button-primary-inv` etc.) instead of one button that you have to style with props?

(is there a way of having types to know what to put where without having to open the implementation in liquid?)

**Comment by vogelino** [comment]
> @vogelino @dnsos opinionated question: How would you guys feel about having multiple buttons that have one design (e.g. `button-primary`, `button-primary-inv` etc.) instead of one button that you have to style with props?

Ich denke das ist eine Idee wäre, um es zu vereinfachen. Was aber dagegen spricht, ist dass man dann nicht DRY ist. Ist aber bei so nen simplen Komponent vielleicht nicht schlimm.
 
> (is there a way of having types to know what to put where without having to open the implementation in liquid?)
Es wäre geil aber nicht dass ich wüsste leider

**Review by dnsos — APPROVED** [review]
Great work!

I'm also split between having it DRY as it is now and changing it to your suggestion @raphael-arce. It is indeed hard in Liquid to know at a quick glance what props can be passed at all. Ultimately I still find it easy _enough_ because the button component consists of only 50 lines. 

> (is there a way of having types to know what to put where without having to open the implementation in liquid?)

I'm also pretty sure there is no way to do that.

**Review by raphael-arce — APPROVED** [review]
Alright, let's keep it like this then 👍

**Review by raphael-arce — APPROVED** [review]
good job, thanks! lgtm 👍

**Comment by vogelino** [comment]
@raphael-arce & @dnsos I added hover and focus styles, as well as a text-link component. I added two npm tailwindcss plugins:
- container queries: Which will help us in the future use the feature
- touch: Which adds support for hover-capable devices with the `hover-hover` previx

And a custom plugin adding a utility for `text-balance` which is a new css feature that allows automatic line length balancing. See https://developer.chrome.com/blog/css-text-wrap-balance/

**Pull request merged**
