### PR TITLE
Refactor/jekyll-to-11ty

### PR DESCRIPTION
**Pull request by ff6347**
This PR migrates the whole site from jekyll to eleventy https://www.11ty.dev/

## Todo:

- [x] Remove build process of grundsicherung and make it just a static asset
- [x] Clean up file copy statements

### CODE REVIEW

**Comment by ff6347** [comment]
Error on page 

https://deploy-preview-109--odis-website.netlify.app/projekte/gdk-analysis/

Footer is missing

**Comment by ff6347** [comment]
> Error on page
> 
> [deploy-preview-109--odis-website.netlify.app/projekte/gdk-analysis](https://deploy-preview-109--odis-website.netlify.app/projekte/gdk-analysis/)
> 
> Footer is missing

fixed

**Comment by Lisa-Stubert** [comment]
nooo what happened here https://deploy-preview-109--odis-website.netlify.app/aktuelles/

**Review by Lisa-Stubert — COMMENTED** [review]
the "remove logging" commit caused an error, aktuelles pages is not working

**Comment by Lisa-Stubert** [comment]
🎉

**Pull request merged**
